apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-settings
  labels:
    {{- include "backstage.labels" . | nindent 4 }}  
data:
    BACKSTAGE_BASE_URL:
    NODE_ENV:
    GITHUB_APP_ID:
    POSTGRES_DATABASE:
    POSTGRES_HOST:
    POSTGRES_PORT:
    POSTGRES_USER:
    AUTH_GITHUB_CLIENT_ID:
    AUTH_GITHUB_WEBHOOK_URL:
    AUTH_GITHUB_WEBHOOK_SECRET: