apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backstage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backstage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backstage
          envFrom:
          - configMapRef:
              name: backstage-settings
          - secretRef:
              name: backstage-secrets
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 7007
            protocol: TCP
          volumeMounts:
          - mountPath: /app/app-config/app-config.production.yaml
            name: backstage-app-config
            subPath: app-confing.production.yaml
      imagePullSecrets:
      - name: pullsecret
      volumes:
      - configMap:
          name: backstage-app-config
        name: backstage-app-config